'use client';

import {lazy, Suspense, useState, useCallback, useEffect} from "react";
import Link from "next/link";
import {copyTextToClipboard, createSecretLink} from '../utils/util';
import wordlist from '../utils/wordlist';

const ShowNewLink = lazy(() => import('./ShowNewLink'));

function LinkReadyFallback() {
    return (
        <p style={{color: 'var(--text-secondary)', padding: '20px 0', textAlign: 'center'}}>
            Preparing secure link...
        </p>
    );
}

const CHARSETS = {
    uppercase: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    lowercase: 'abcdefghijklmnopqrstuvwxyz',
    numbers: '0123456789',
    symbols: '!@#$%^&*()-_=+[]{}|;:,.<>?',
};

// SEO preset configurations keyed by route path
const PRESETS = {
    '/password-generator': {
        title: 'Strong Password Generator',
        subtitle: 'Generate strong passwords and passphrases in your browser. Nothing leaves your device.',
        length: 20,
        mode: 'password',
        options: { uppercase: true, lowercase: true, numbers: true, symbols: true },
        seoHeading: 'Free Online Strong Password Generator',
        seoText: 'Create secure, random passwords instantly with our free password generator. Every password is generated entirely in your browser using cryptographic randomness — nothing is ever sent to a server. Choose your preferred length, character types, or switch to memorable passphrases. Strong passwords are your first line of defense against unauthorized access to your accounts.',
        seoSections: [
            {
                heading: 'Why random passwords matter',
                text: 'Reusing passwords or choosing predictable ones is the leading cause of account breaches. Attackers use credential-stuffing tools that test billions of leaked username-password pairs across popular services. A single reused password can compromise your email, banking, and social media accounts in minutes. A truly random password — one generated by a cryptographic algorithm rather than a human brain — eliminates the patterns that attackers exploit. Each password from this generator is statistically independent, so knowing one reveals nothing about the next.',
            },
            {
                heading: 'How this generator works',
                text: 'The generator uses the Web Crypto API (window.crypto.getRandomValues), the same cryptographic random number generator that your browser relies on for TLS connections. When you click "Regenerate", the tool builds a character pool from your selected options (uppercase, lowercase, digits, symbols), draws random indices, and assembles the password entirely in memory. No network request is made — your password never leaves the page. The source code is open and auditable on GitHub.',
            },
            {
                heading: 'How long should a password be?',
                text: 'Password length is the single biggest factor in security. Each additional character multiplies the number of possible combinations exponentially. An 8-character password using all character types has about 47 bits of entropy and can be brute-forced in hours. A 12-character password jumps to about 71 bits — enough for most accounts. A 16-character password provides roughly 95 bits, making brute-force attacks computationally infeasible with current hardware. For high-value accounts like email, banking, and password manager vaults, we recommend 16 characters or more.',
            },
            {
                heading: 'Password vs passphrase: which should you use?',
                text: 'Random passwords are ideal when you paste them from a password manager — maximum entropy per character, no need to memorize. Passphrases are better when you need to type the password by hand: logging into your computer, entering a WiFi key on a smart TV, or unlocking your password manager vault. A 5-word passphrase like "Timber-Canoe-Frozen-Maple-97" provides over 60 bits of entropy while remaining human-readable. The best approach is to use both: passphrases for the few passwords you type daily, and random passwords (stored in a manager) for everything else.',
            },
        ],
        faq: [
            { q: 'Is this password generator safe to use?', a: 'Yes. Passwords are generated entirely in your browser using the Web Crypto API. Nothing is transmitted to any server. You can verify this by disconnecting from the internet — the generator still works. The code is open source and auditable.' },
            { q: 'How do I remember a random password?', a: 'You don\'t need to. Use a password manager like Bitwarden, 1Password, or KeePass to store your passwords. The only password you need to memorize is your master password — for that, use the passphrase mode to create something memorable.' },
            { q: 'What makes a password strong?', a: 'Three factors: length (12+ characters minimum), randomness (generated by an algorithm, not chosen by a human), and uniqueness (never reused across accounts). A 16-character random password with mixed character types is virtually uncrackable.' },
            { q: 'Should I include symbols in my password?', a: 'When possible, yes. Symbols increase the character pool from 62 to 94 characters, adding roughly 6 bits of entropy at 16 characters. However, some older systems don\'t accept certain symbols. If a site rejects your password, try regenerating without symbols or use a longer alphanumeric password instead.' },
        ],
    },
    '/password-generator-14-characters': {
        title: '14-Character Password Generator',
        subtitle: 'Quick 14-character password with letters, numbers, and symbols.',
        length: 14,
        mode: 'password',
        options: { uppercase: true, lowercase: true, numbers: true, symbols: true },
        seoHeading: 'Generate a 14-Character Password with Symbols',
        seoText: 'A 14-character password with mixed character types provides solid security for most online accounts. Many services require at least 8 characters, but 14 is the minimum recommended by cybersecurity professionals. This generator creates passwords with uppercase and lowercase letters, digits, and symbols — all generated locally in your browser for maximum privacy.',
        seoSections: [
            {
                heading: 'Why 14 characters?',
                text: 'Fourteen characters is a practical sweet spot for everyday accounts. Using all four character types (uppercase, lowercase, digits, symbols), a 14-character password provides approximately 91 bits of entropy. At current brute-force speeds — even using GPU clusters — cracking a password with 91 bits of entropy would take longer than the age of the universe. Most websites and services accept 14-character passwords without issues, making this length both secure and compatible.',
            },
            {
                heading: 'How strong is a 14-character password?',
                text: 'Strength depends on the character pool. With all types enabled (94 characters), 14 characters yields 91 bits of entropy. With only lowercase letters (26 characters), the same length gives just 66 bits. That\'s why mixing character types matters. For context: NIST guidelines recommend a minimum of 8 characters for user-chosen passwords but suggest longer randomly generated ones. Security professionals and compliance frameworks like SOC 2 typically recommend 12-16 characters as a minimum for service accounts and privileged access.',
            },
            {
                heading: 'When is 14 characters enough?',
                text: 'For most personal accounts — social media, shopping, streaming, forums — a 14-character random password is more than sufficient. The realistic threat model for these accounts isn\'t brute-force attacks against your specific password; it\'s credential stuffing from database leaks and phishing. A unique, random 14-character password defeats both. For high-value targets like email, banking, cloud infrastructure, or your password manager master password, consider stepping up to 16-20 characters for extra margin.',
            },
        ],
        faq: [
            { q: 'Is 14 characters enough for a secure password?', a: 'Yes, for the vast majority of use cases. A 14-character password with mixed character types has about 91 bits of entropy — well beyond what\'s needed to resist brute-force attacks. The bigger risk is password reuse, not password length.' },
            { q: 'What sites require exactly 14 characters?', a: 'Few sites set exact requirements, but many set minimums of 8-12 characters with maximum limits of 16-128. A 14-character password comfortably meets almost all minimum requirements while staying well under maximum limits.' },
            { q: 'Should I use 14 or 16 characters?', a: 'If you\'re storing passwords in a manager and don\'t need to type them, go with 16+ characters for extra margin. If you\'re choosing 14 characters for compatibility or convenience, that\'s completely fine for standard accounts.' },
            { q: 'Can I use this password for my WiFi?', a: 'You can, but consider using the WiFi Password Generator instead — it creates passwords without confusing symbols, making them easier to type on phones and smart TVs.' },
        ],
    },
    '/passphrase-generator': {
        title: 'Passphrase Generator',
        subtitle: 'Generate memorable multi-word passphrases that are easy to type.',
        length: 16,
        mode: 'passphrase',
        options: { uppercase: true, lowercase: true, numbers: true, symbols: true },
        wordCount: 5,
        seoHeading: 'Memorable Passphrase Generator',
        seoText: 'Passphrases combine multiple random words into a single password that is both highly secure and easy to remember. A 4-5 word passphrase can provide over 50 bits of entropy while remaining human-friendly. Our passphrase generator picks words from a curated list using cryptographic randomness, so every combination is unique. Passphrases are ideal for master passwords, device logins, and any situation where you need to type your password by hand.',
        seoSections: [
            {
                heading: 'What is a passphrase?',
                text: 'A passphrase is a password made of multiple random words strung together, like "Timber-Canoe-Frozen-Maple-97". Unlike traditional passwords, passphrases are designed to be memorized and typed by humans while maintaining high entropy. The concept was popularized by Diceware, a method where you roll physical dice to select words from a list. This generator applies the same principle using cryptographic randomness instead of dice, producing results that are statistically equivalent in security.',
            },
            {
                heading: 'How secure are passphrases?',
                text: 'Security depends on the word count and list size. This generator uses a curated list of common English words. Each word adds approximately 11-13 bits of entropy depending on the list size. A 4-word passphrase provides about 50 bits of entropy — adequate for low-value accounts. A 5-word passphrase gives about 64 bits — good for most purposes. For high-value targets like your password manager vault, use 6 or more words (77+ bits). Adding a number and capitalizing words further increases entropy by several bits.',
            },
            {
                heading: 'Passphrase vs password: when to use each',
                text: 'Use a passphrase when you need to type the password from memory: your computer login, phone lock screen, password manager master password, WiFi access, or full-disk encryption. Use a random character password when you\'ll paste it from a password manager — this maximizes entropy per character. The ideal setup is a strong passphrase for your password manager vault, with unique random passwords for every other account stored inside it.',
            },
            {
                heading: 'Tips for stronger passphrases',
                text: 'Avoid famous quotes, song lyrics, or book titles — attackers build dictionaries from cultural references. Always use randomly generated word combinations, not phrases you invent. Use at least 4 words; 5-6 is better. Add a number or symbol between words for extra entropy. Capitalize at least one word. Never reuse a passphrase across accounts. Consider adding one intentional misspelling (e.g., "Timbr" instead of "Timber") for an additional layer of unpredictability that defeats dictionary attacks.',
            },
        ],
        faq: [
            { q: 'Are passphrases more secure than passwords?', a: 'They can be. A 5-word passphrase has roughly 64 bits of entropy — comparable to a 10-character random password. The advantage is memorability: you can remember "Timber-Canoe-Frozen-Maple-97" but not "kX9#mR2$pL". For maximum security per character, random passwords win. For something you need to type and remember, passphrases are superior.' },
            { q: 'How many words should my passphrase have?', a: 'At minimum 4 words for basic accounts. Use 5 words for important accounts (email, banking). Use 6+ words for your password manager master password or full-disk encryption. Each additional word roughly doubles the number of possible combinations.' },
            { q: 'Can I modify the generated passphrase?', a: 'You can, but be careful. Adding a word or number increases security. Removing a word decreases it. Replacing a random word with a personally meaningful one (like a pet\'s name) can weaken the passphrase if an attacker knows you.' },
            { q: 'What separator should I use between words?', a: 'Any separator works. Hyphens are popular because they\'re easy to type. Spaces work if the system allows them. The separator itself adds minimal entropy — it\'s the word count that matters most.' },
        ],
    },
    '/password-generator-16-characters': {
        title: '16-Character Password Generator',
        subtitle: 'Generate a strong 16-character password instantly.',
        length: 16,
        mode: 'password',
        options: { uppercase: true, lowercase: true, numbers: true, symbols: true },
        seoHeading: 'Generate a 16-Character Password',
        seoText: 'A 16-character password strikes the ideal balance between security and usability. With a mix of uppercase letters, lowercase letters, numbers, and symbols, a 16-character password provides approximately 105 bits of entropy — far beyond what any brute-force attack can crack in a human lifetime. Many security standards including NIST and OWASP recommend at least 12-16 characters. This generator creates your password locally in the browser using cryptographic randomness, so it never leaves your device.',
        seoSections: [
            {
                heading: 'Why 16 characters is the security sweet spot',
                text: 'Security professionals increasingly recommend 16 characters as the standard length for generated passwords. The math is compelling: using all character types (94 possible characters per position), a 16-character password has 94^16 possible combinations — approximately 3.7 × 10^31. Even a billion guesses per second would take over a trillion years. Meanwhile, 16 characters fits within the password length limits of virtually every service. It\'s long enough to be uncrackable, short enough to be universally compatible.',
            },
            {
                heading: 'Brute-force resistance by password length',
                text: 'Here\'s how password length affects crack time (assuming all character types and 10 billion guesses per second): 8 characters — about 19 hours. 10 characters — about 7 months. 12 characters — about 5,000 years. 14 characters — about 46 million years. 16 characters — about 400 billion years. As you can see, each pair of additional characters increases resistance by roughly 4-5 orders of magnitude. The jump from 12 to 16 characters is the difference between "possibly crackable in your lifetime" and "completely infeasible."',
            },
            {
                heading: 'Compliance and industry standards',
                text: 'NIST Special Publication 800-63B recommends allowing at least 64-character passwords and no longer mandates periodic password changes for randomly generated credentials. OWASP recommends a minimum of 12 characters. PCI DSS 4.0 requires at least 12 characters for system accounts. SOC 2 auditors commonly look for 16-character minimums on service accounts and API keys. Using a 16-character generated password meets or exceeds all major compliance frameworks.',
            },
        ],
        faq: [
            { q: 'Is 16 characters overkill for personal accounts?', a: 'Not at all. If you\'re using a password manager (which you should be), the length costs you nothing — you never type it manually. 16 characters provides a substantial safety margin against future advances in computing power, including potential quantum computing attacks on weaker passwords.' },
            { q: 'How does 16 characters compare to 12?', a: 'With all character types enabled, 16 characters gives about 105 bits of entropy vs 78 bits for 12 characters. That\'s roughly 10 million times harder to crack. Since password managers handle the complexity, there\'s no reason not to use the longer option.' },
            { q: 'Will all websites accept 16-character passwords?', a: 'Nearly all modern websites accept 16 characters. A few legacy systems have maximum limits of 12 or even 8 characters — in those cases, use the longest length allowed and consider the 14-character generator as an alternative.' },
            { q: 'Do I need symbols in a 16-character password?', a: 'Symbols help but aren\'t critical at this length. A 16-character alphanumeric password (no symbols) has about 95 bits of entropy — still very strong. Adding symbols bumps it to 105 bits. If a site doesn\'t accept symbols, an alphanumeric 16-character password is perfectly secure.' },
        ],
    },
    '/wifi-password-generator': {
        title: 'WiFi Password Generator',
        subtitle: 'Generate strong WiFi passwords that are secure yet easy to share.',
        length: 16,
        mode: 'password',
        options: { uppercase: true, lowercase: true, numbers: true, symbols: false },
        seoHeading: 'Generate a Strong WiFi Password',
        seoText: 'Your WiFi password protects your entire home or office network. A weak WiFi password can be cracked in minutes using widely available tools, giving attackers access to all devices on your network. Our WiFi password generator creates strong, random passwords without confusing symbols — making them easy to read and type on phones, smart TVs, and IoT devices. Generated entirely in your browser with cryptographic randomness. For maximum security, change your WiFi password periodically and use WPA3 if your router supports it.',
        seoSections: [
            {
                heading: 'Why WiFi passwords need special treatment',
                text: 'WiFi passwords are different from website passwords in two important ways. First, you need to type them manually on every device — phones, laptops, smart TVs, game consoles, printers, IoT devices. Symbols like #, @, and $ are hard to find on TV remotes and some device keyboards, which is why this generator uses only letters and numbers. Second, WiFi passwords can be attacked offline: an attacker captures the WPA handshake and brute-forces it on their own hardware without rate limiting. This makes length and randomness especially critical.',
            },
            {
                heading: 'WPA2 vs WPA3: what your password protects',
                text: 'With WPA2 (still the most common protocol), your password is hashed using PBKDF2 with 4,096 iterations of SHA-1. A determined attacker with a GPU cluster can test millions of guesses per second against the captured handshake. An 8-character alphanumeric password can be cracked in days. A 16-character one pushes the time well beyond feasibility. WPA3 uses SAE (Simultaneous Authentication of Equals), which makes offline brute-force attacks significantly harder. If your router supports WPA3, enable it — but use a strong password regardless.',
            },
            {
                heading: 'How to change your WiFi password',
                text: 'Log into your router\'s admin panel (usually at 192.168.0.1 or 192.168.1.1 in your browser). Navigate to the Wireless or WiFi settings section. Look for the password or passkey field under your network name (SSID). Paste or type your new password, save the settings, and reconnect all your devices. Consider generating a QR code for the new password so guests can connect by scanning instead of typing. Most phones can generate WiFi QR codes from the settings app.',
            },
            {
                heading: 'How to share your WiFi password securely',
                text: 'Avoid writing your WiFi password on a sticky note or whiteboard where anyone passing by can see it. Instead, share it through an encrypted one-time link that self-destructs after being read — use the "Share as link" button above. For in-person sharing, a WiFi QR code is convenient and secure. On iPhone, you can share WiFi passwords directly to nearby Apple devices through the built-in sharing feature. On Android, use the share button in WiFi settings to generate a QR code.',
            },
        ],
        faq: [
            { q: 'Why no symbols in WiFi passwords?', a: 'Most WiFi passwords are typed on devices with limited keyboards — smart TVs, game consoles, IoT devices. Symbols like @#$% are hard to locate on these keyboards and slow down the process. A 16-character alphanumeric password still provides about 95 bits of entropy, which is more than sufficient for WiFi security.' },
            { q: 'How long should a WiFi password be?', a: 'At least 12 characters, ideally 16 or more. WiFi passwords can be attacked offline (the attacker doesn\'t need to stay connected to your network), so they need more length than typical website passwords. Our default of 16 characters provides a strong security margin.' },
            { q: 'How often should I change my WiFi password?', a: 'Change it when a device is lost or stolen, when someone who knows the password no longer needs access, or if you suspect unauthorized access. For home networks with WPA3, routine changes aren\'t strictly necessary. For WPA2 networks in shared environments (offices, rentals), consider changing it every 3-6 months.' },
            { q: 'Can someone hack my WiFi with a strong password?', a: 'With a 16-character random password and WPA2/WPA3, brute-forcing the password is computationally infeasible. Attackers would need to exploit router firmware vulnerabilities or use social engineering instead. Keep your router firmware updated and disable WPS (WiFi Protected Setup) for best security.' },
        ],
    },
    '/api-key-generator': {
        title: 'API Key Generator',
        subtitle: 'Generate random API keys and tokens for your applications.',
        length: 32,
        mode: 'password',
        options: { uppercase: true, lowercase: true, numbers: true, symbols: false },
        seoHeading: 'Generate Random API Keys and Tokens',
        seoText: 'API keys and tokens need to be long, random, and unpredictable. Our API key generator creates cryptographically random strings using the Web Crypto API built into your browser — the same randomness source used for TLS encryption. The default 32-character alphanumeric format works with virtually any API or service. No symbols by default to avoid URL-encoding issues. Everything is generated client-side — your keys never touch a server. Need to share the key securely? Use the built-in share button to create an encrypted one-time link.',
        seoSections: [
            {
                heading: 'What are API keys used for?',
                text: 'API keys serve as authentication tokens for machine-to-machine communication. They identify your application when calling external services — payment processors, cloud platforms, email delivery services, databases, and third-party integrations. Unlike user passwords, API keys are typically stored in environment variables, configuration files, or secrets managers and are never typed by hand. This is why length and randomness matter more than memorability. A 32-character alphanumeric key provides about 190 bits of entropy — far more than any attacker can brute-force.',
            },
            {
                heading: 'API key best practices',
                text: 'Never hard-code API keys in source code — they end up in version control history even if you delete them later. Use environment variables or a secrets manager (AWS Secrets Manager, HashiCorp Vault, Doppler). Rotate keys periodically and immediately if a key is exposed. Use different keys for development, staging, and production environments. Set the most restrictive permissions possible for each key. Monitor API key usage for anomalies. When sharing keys with team members, use encrypted one-time links instead of Slack messages or emails that remain in chat history.',
            },
            {
                heading: 'How to share API keys with your team',
                text: 'Sharing API keys through Slack, email, or team chat is one of the most common security mistakes in software development. These messages persist in search history, backups, and third-party data exports. Instead, use the "Share as link" button above to create an encrypted one-time link. The recipient clicks the link, copies the key, and the link self-destructs. The key is encrypted end-to-end so even our server never sees the plaintext. For ongoing team access, use a secrets manager that provides audit logs and role-based access control.',
            },
            {
                heading: 'Token formats for different use cases',
                text: 'Different systems expect different token formats. For general API keys, 32-character alphanumeric strings (our default) work everywhere. For URL-safe tokens, avoid symbols since characters like + and / need percent-encoding. For JWT secrets, use 32+ characters for HMAC-SHA256. For database passwords, 24-32 alphanumeric characters are typical. For webhook signing secrets, 32-64 characters is standard. Adjust the length slider above based on your needs — when in doubt, longer is better.',
            },
        ],
        faq: [
            { q: 'Why 32 characters by default?', a: 'A 32-character alphanumeric string provides about 190 bits of entropy — well beyond the 128-bit security level recommended for cryptographic keys. 32 characters is also a common convention for API keys (matching the hex representation of a 128-bit value) and is accepted by virtually all services.' },
            { q: 'Why no symbols in API keys?', a: 'Symbols cause problems in many technical contexts. They require URL-encoding in query strings, can break shell scripts if not properly quoted, and may be rejected by systems that expect alphanumeric-only tokens. At 32 characters, the entropy from alphanumeric characters alone is more than sufficient.' },
            { q: 'Is it safe to generate API keys in a browser?', a: 'Yes. This generator uses the Web Crypto API (crypto.getRandomValues), the same cryptographically secure random number generator your browser uses for HTTPS connections. The key is generated in your browser\'s memory and never transmitted anywhere. You can disconnect from the internet and the generator still works.' },
            { q: 'How often should I rotate API keys?', a: 'Rotate immediately if a key is exposed (committed to a public repo, shared in an unencrypted channel). For routine rotation, every 90 days is a common policy. Automated rotation through a secrets manager is ideal. Always have a plan for rotating keys without downtime — most services support having two active keys simultaneously for this purpose.' },
        ],
    },
};

// All SEO pages to link to (excluding the current page)
const SEO_LINKS = [
    { path: '/password-generator', label: 'Password Generator', desc: 'All-purpose password & passphrase tool' },
    { path: '/passphrase-generator', label: 'Passphrase Generator', desc: 'Memorable multi-word passphrases' },
    { path: '/password-generator-14-characters', label: '14-Character Password', desc: 'Quick passwords with symbols for most sites' },
    { path: '/password-generator-16-characters', label: '16-Character Password', desc: 'The sweet spot of security and usability' },
    { path: '/wifi-password-generator', label: 'WiFi Password Generator', desc: 'Easy-to-type passwords for your network' },
    { path: '/api-key-generator', label: 'API Key Generator', desc: 'Random tokens and keys for developers' },
];

function secureRandom(max) {
    const arr = new Uint32Array(1);
    crypto.getRandomValues(arr);
    return arr[0] % max;
}

function generatePassword(length, options) {
    let chars = '';
    if (options.uppercase) chars += CHARSETS.uppercase;
    if (options.lowercase) chars += CHARSETS.lowercase;
    if (options.numbers) chars += CHARSETS.numbers;
    if (options.symbols) chars += CHARSETS.symbols;
    if (!chars) chars = CHARSETS.lowercase;

    let result = '';
    for (let i = 0; i < length; i++) {
        result += chars[secureRandom(chars.length)];
    }
    return result;
}

function generatePassphrase(wordCount, separator, capitalize, includeNumber) {
    const words = [];
    for (let i = 0; i < wordCount; i++) {
        let word = wordlist[secureRandom(wordlist.length)];
        if (capitalize) {
            word = word.charAt(0).toUpperCase() + word.slice(1);
        }
        words.push(word);
    }
    let result = words.join(separator);
    if (includeNumber) {
        result += separator + secureRandom(1000);
    }
    return result;
}

function estimateEntropy(password) {
    let poolSize = 0;
    if (/[a-z]/.test(password)) poolSize += 26;
    if (/[A-Z]/.test(password)) poolSize += 26;
    if (/[0-9]/.test(password)) poolSize += 10;
    if (/[^a-zA-Z0-9]/.test(password)) poolSize += 32;
    if (poolSize === 0) return 0;
    return Math.floor(password.length * Math.log2(poolSize));
}

function getStrength(entropy) {
    if (entropy < 40) return { label: 'Weak', color: 'var(--danger)', percent: 20 };
    if (entropy < 60) return { label: 'Fair', color: 'var(--warning)', percent: 40 };
    if (entropy < 80) return { label: 'Good', color: 'var(--success)', percent: 60 };
    if (entropy < 120) return { label: 'Strong', color: '#047857', percent: 80 };
    return { label: 'Very strong', color: '#065F46', percent: 100 };
}

export default function PasswordGenerator({ presetPath }) {
    const preset = PRESETS[presetPath] || PRESETS['/password-generator'];

    const [mode, setMode] = useState(preset.mode);
    const [copied, setCopied] = useState(false);
    const [generated, setGenerated] = useState('');
    const [isSharing, setIsSharing] = useState(false);
    const [sharedLink, setSharedLink] = useState('');

    // Password options
    const [length, setLength] = useState(preset.length);
    const [options, setOptions] = useState(preset.options);

    // Passphrase options
    const [wordCount, setWordCount] = useState(preset.wordCount || 4);
    const [separator, setSeparator] = useState('-');
    const [capitalize, setCapitalize] = useState(true);
    const [includeNumber, setIncludeNumber] = useState(true);

    const generate = useCallback(() => {
        setCopied(false);
        if (mode === 'password') {
            setGenerated(generatePassword(length, options));
        } else {
            setGenerated(generatePassphrase(wordCount, separator, capitalize, includeNumber));
        }
    }, [mode, length, options, wordCount, separator, capitalize, includeNumber]);

    useEffect(() => {
        generate();
    }, [generate]);

    const handleCopy = async () => {
        const didCopy = await copyTextToClipboard(generated);
        if (didCopy) {
            setCopied(true);
            setTimeout(() => setCopied(false), 3000);
        }
    };

    const handleShare = async () => {
        if (!generated || isSharing) {
            return;
        }

        setIsSharing(true);

        try {
            const {link} = await createSecretLink(generated);
            setIsSharing(false);
            setSharedLink(link);
            return;
        } catch (error) {}

        setIsSharing(false);
    };

    const toggleOption = (key) => {
        const next = {...options, [key]: !options[key]};
        const anyOn = Object.values(next).some(Boolean);
        if (anyOn) setOptions(next);
    };

    const otherPages = SEO_LINKS.filter(l => l.path !== presetPath);

    if (sharedLink) {
        return (
            <Suspense fallback={<LinkReadyFallback />}>
                <ShowNewLink
                    newLink={sharedLink}
                    onReset={() => setSharedLink('')}
                />
            </Suspense>
        );
    }

    return (
        <div>
            <div className="gen-header">
                <h1 className="gen-title">{preset.title}</h1>
                <p className="gen-subtitle">{preset.subtitle}</p>
            </div>

            <div className="gen-tabs">
                <button
                    className={`gen-tab ${mode === 'password' ? 'gen-tab-active' : ''}`}
                    onClick={() => setMode('password')}
                    type="button"
                >Random Password</button>
                <button
                    className={`gen-tab ${mode === 'passphrase' ? 'gen-tab-active' : ''}`}
                    onClick={() => setMode('passphrase')}
                    type="button"
                >Passphrase</button>
            </div>

            <div className="gen-output" onClick={handleCopy} title="Click to copy">
                <code className="gen-output-text">{generated}</code>
            </div>

            {generated && (() => {
                const entropy = estimateEntropy(generated);
                const strength = getStrength(entropy);
                return (
                    <div className="gen-meter">
                        <div className="gen-meter-bar">
                            <div
                                className="gen-meter-fill"
                                style={{ width: strength.percent + '%', background: strength.color }}
                            />
                        </div>
                        <div className="gen-meter-info">
                            <span className="gen-meter-label" style={{ color: strength.color }}>{strength.label}</span>
                            <span className="gen-meter-bits">{entropy} bits of entropy</span>
                        </div>
                    </div>
                );
            })()}

            <div className="gen-actions">
                <button className="btn btn-secondary" onClick={generate} type="button">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M23 4v6h-6"/><path d="M1 20v-6h6"/>
                        <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/>
                    </svg>
                    Regenerate
                </button>
                <button className="btn btn-success" onClick={handleCopy} type="button">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                        {copied
                            ? <polyline points="20 6 9 17 4 12"/>
                            : <><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></>
                        }
                    </svg>
                    {copied ? "Copied!" : "Copy"}
                </button>
                <button className="btn btn-primary" onClick={handleShare} type="button" disabled={!generated || isSharing}>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/>
                        <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>
                    </svg>
                    {isSharing ? 'Creating...' : 'Share as link'}
                </button>
            </div>

            <div className="gen-options">
                {mode === 'password' ? (
                    <>
                        <div className="gen-option-row">
                            <label className="form-label" htmlFor="gen-length">
                                Length: <strong>{length}</strong>
                            </label>
                            <input
                                className="gen-slider"
                                id="gen-length"
                                type="range"
                                min="8"
                                max="128"
                                value={length}
                                onChange={(e) => setLength(Number(e.target.value))}
                            />
                        </div>
                        <div className="gen-checkboxes">
                            {Object.keys(CHARSETS).map((key) => (
                                <label key={key} className="gen-checkbox">
                                    <input
                                        type="checkbox"
                                        checked={options[key]}
                                        onChange={() => toggleOption(key)}
                                    />
                                    <span className="gen-checkbox-label">{key.charAt(0).toUpperCase() + key.slice(1)}</span>
                                </label>
                            ))}
                        </div>
                    </>
                ) : (
                    <>
                        <div className="gen-option-row">
                            <label className="form-label" htmlFor="gen-words">Words</label>
                            <select
                                className="form-select"
                                id="gen-words"
                                value={wordCount}
                                onChange={(e) => setWordCount(Number(e.target.value))}
                            >
                                {[3,4,5,6,7,8].map(n => (
                                    <option key={n} value={n}>{n} words</option>
                                ))}
                            </select>
                        </div>
                        <div className="gen-option-row">
                            <label className="form-label" htmlFor="gen-sep">Separator</label>
                            <select
                                className="form-select"
                                id="gen-sep"
                                value={separator}
                                onChange={(e) => setSeparator(e.target.value)}
                            >
                                <option value="-">Hyphen (-)</option>
                                <option value=" ">Space</option>
                                <option value=".">Dot (.)</option>
                                <option value="_">Underscore (_)</option>
                            </select>
                        </div>
                        <div className="gen-checkboxes">
                            <label className="gen-checkbox">
                                <input
                                    type="checkbox"
                                    checked={capitalize}
                                    onChange={() => setCapitalize(!capitalize)}
                                />
                                <span className="gen-checkbox-label">Capitalize words</span>
                            </label>
                            <label className="gen-checkbox">
                                <input
                                    type="checkbox"
                                    checked={includeNumber}
                                    onChange={() => setIncludeNumber(!includeNumber)}
                                />
                                <span className="gen-checkbox-label">Include number</span>
                            </label>
                        </div>
                    </>
                )}
            </div>

            {/* SEO content section */}
            <section className="gen-seo">
                <h2 className="gen-seo-heading">{preset.seoHeading}</h2>
                <p className="gen-seo-text">{preset.seoText}</p>

                {preset.seoSections && preset.seoSections.map((section, i) => (
                    <div key={i}>
                        <h3 className="gen-seo-subheading">{section.heading}</h3>
                        <p className="gen-seo-text">{section.text}</p>
                    </div>
                ))}

                {preset.faq && preset.faq.length > 0 && (
                    <div className="gen-faq">
                        <h3 className="gen-seo-subheading">Frequently asked questions</h3>
                        <dl className="gen-faq-list">
                            {preset.faq.map((item, i) => (
                                <div key={i} className="gen-faq-item">
                                    <dt className="gen-faq-q">{item.q}</dt>
                                    <dd className="gen-faq-a">{item.a}</dd>
                                </div>
                            ))}
                        </dl>
                    </div>
                )}
            </section>

            {/* Internal links to other generator pages */}
            <nav className="gen-related" aria-label="Related password tools">
                <h3 className="gen-related-heading">More password tools</h3>
                <div className="gen-related-grid">
                    {otherPages.map(page => (
                        <Link key={page.path} href={page.path} className="gen-related-card">
                            <span className="gen-related-title">{page.label}</span>
                            <span className="gen-related-desc">{page.desc}</span>
                        </Link>
                    ))}
                </div>
            </nav>
        </div>
    );
}
