import InlineCss from '../../components/InlineCss';
import PasswordGenerator from '../../components/PasswordGenerator';
import {absoluteUrl, siteHost} from '../../utils/siteConfig';

export const metadata = {
    title: `Strong Password Generator — Free & Secure | ${siteHost}`,
    description: 'Generate strong, random passwords instantly in your browser. Cryptographically secure, nothing sent to a server. Choose length, symbols, or passphrases. Free and open source.',
    alternates: { canonical: '/password-generator' },
    openGraph: {
        title: `Strong Password Generator — Free & Secure | ${siteHost}`,
        description: 'Generate strong, random passwords instantly in your browser. Cryptographically secure, nothing sent to a server.',
        url: '/password-generator',
        images: [{ url: '/og-image.png', width: 1200, height: 630, alt: 'Free Password Generator' }],
    },
};

const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'Strong Password Generator',
    url: absoluteUrl('/password-generator'),
    description: 'Generate strong, random passwords and passphrases in your browser. Client-side only, nothing sent to a server.',
    applicationCategory: 'SecurityApplication',
    operatingSystem: 'Any',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
};

const breadcrumbJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://1time.io' },
        { '@type': 'ListItem', position: 2, name: 'Strong Password Generator', item: 'https://1time.io/password-generator' },
    ],
};

const faqJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
        { '@type': 'Question', name: 'Is this password generator safe to use?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Passwords are generated entirely in your browser using the Web Crypto API. Nothing is transmitted to any server. You can verify this by disconnecting from the internet — the generator still works. The code is open source and auditable.' } },
        { '@type': 'Question', name: 'How do I remember a random password?', acceptedAnswer: { '@type': 'Answer', text: 'You don\'t need to. Use a password manager like Bitwarden, 1Password, or KeePass to store your passwords. The only password you need to memorize is your master password — for that, use the passphrase mode to create something memorable.' } },
        { '@type': 'Question', name: 'What makes a password strong?', acceptedAnswer: { '@type': 'Answer', text: 'Three factors: length (12+ characters minimum), randomness (generated by an algorithm, not chosen by a human), and uniqueness (never reused across accounts). A 16-character random password with mixed character types is virtually uncrackable.' } },
        { '@type': 'Question', name: 'Should I include symbols in my password?', acceptedAnswer: { '@type': 'Answer', text: 'When possible, yes. Symbols increase the character pool from 62 to 94 characters, adding roughly 6 bits of entropy at 16 characters. However, some older systems don\'t accept certain symbols. If a site rejects your password, try regenerating without symbols or use a longer alphanumeric password instead.' } },
    ],
};

export default function PasswordGeneratorPage() {
    return (
        <>
            <InlineCss file="styles/generator.css" />
            <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
            <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />
            <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
            <PasswordGenerator presetPath="/password-generator" />
        </>
    );
}
